"""add meal attendance module

Revision ID: 51f59d2075d9
Revises: 4b91d3a7c0e2
Create Date: 2026-09-09 15:39:14.264598

"""

import sqlalchemy as sa
from alembic import op

import mealie.db.migration_types

# revision identifiers, used by Alembic.
revision = "51f59d2075d9"
down_revision: str | None = "4b91d3a7c0e2"
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mealplan_attendance_settings",
        sa.Column("id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("group_id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("household_id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("deadline_mode", sa.String(), nullable=False),
        sa.Column("deadline_weekday", sa.Integer(), nullable=False),
        sa.Column("deadline_time", sa.Time(), nullable=False),
        sa.Column("deadline_lead_days", sa.Integer(), nullable=False),
        sa.Column("timezone", sa.String(), nullable=False),
        sa.Column("auto_lock", sa.Boolean(), nullable=False),
        sa.Column("reminder_enabled", sa.Boolean(), nullable=False),
        sa.Column("reminder_hours_before", sa.Integer(), nullable=False),
        sa.Column("entry_types", sa.String(), nullable=False),
        sa.Column("created_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.Column("update_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["households.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("household_id", name="mealplan_attendance_settings_household_key"),
    )
    with op.batch_alter_table("mealplan_attendance_settings", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_mealplan_attendance_settings_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_mealplan_attendance_settings_group_id"), ["group_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_mealplan_attendance_settings_household_id"), ["household_id"], unique=False
        )

    op.create_table(
        "mealplan_participants",
        sa.Column("id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("group_id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("household_id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("user_id", mealie.db.migration_types.GUID(), nullable=True),
        sa.Column("parent_id", mealie.db.migration_types.GUID(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("default_attending", sa.Boolean(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.Column("update_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["households.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["mealplan_participants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("household_id", "user_id", name="mealplan_participant_household_user_key"),
    )
    with op.batch_alter_table("mealplan_participants", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_mealplan_participants_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_mealplan_participants_group_id"), ["group_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_mealplan_participants_household_id"), ["household_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_mealplan_participants_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_mealplan_participants_parent_id"), ["parent_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_mealplan_participants_user_id"), ["user_id"], unique=False)

    op.create_table(
        "mealplan_recipe_suggestions",
        sa.Column("id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("group_id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("household_id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("recipe_id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("created_by_id", mealie.db.migration_types.GUID(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("note", sa.String(), nullable=True),
        sa.Column("created_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.Column("update_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["households.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("household_id", "recipe_id", "created_by_id", name="mealplan_suggestion_recipe_user_key"),
    )
    with op.batch_alter_table("mealplan_recipe_suggestions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_mealplan_recipe_suggestions_created_at"), ["created_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_mealplan_recipe_suggestions_created_by_id"), ["created_by_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_mealplan_recipe_suggestions_group_id"), ["group_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_mealplan_recipe_suggestions_household_id"), ["household_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_mealplan_recipe_suggestions_recipe_id"), ["recipe_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_mealplan_recipe_suggestions_status"), ["status"], unique=False)

    op.create_table(
        "mealplan_absences",
        sa.Column("id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("group_id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("household_id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("participant_id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("reason", sa.String(), nullable=False),
        sa.Column("note", sa.String(), nullable=True),
        sa.Column("created_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.Column("update_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["households.id"],
        ),
        sa.ForeignKeyConstraint(
            ["participant_id"],
            ["mealplan_participants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("mealplan_absences", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_mealplan_absences_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_mealplan_absences_end_date"), ["end_date"], unique=False)
        batch_op.create_index(batch_op.f("ix_mealplan_absences_group_id"), ["group_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_mealplan_absences_household_id"), ["household_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_mealplan_absences_participant_id"), ["participant_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_mealplan_absences_start_date"), ["start_date"], unique=False)

    op.create_table(
        "mealplan_attendance",
        sa.Column("id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("group_id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("household_id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("mealplan_id", sa.Integer(), nullable=False),
        sa.Column("participant_id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("guest_count", sa.Integer(), nullable=False),
        sa.Column("note", sa.String(), nullable=True),
        sa.Column("responded_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.Column("created_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.Column("update_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["households.id"],
        ),
        sa.ForeignKeyConstraint(
            ["mealplan_id"],
            ["group_meal_plans.id"],
        ),
        sa.ForeignKeyConstraint(
            ["participant_id"],
            ["mealplan_participants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("mealplan_id", "participant_id", name="mealplan_attendance_mealplan_participant_key"),
    )
    with op.batch_alter_table("mealplan_attendance", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_mealplan_attendance_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_mealplan_attendance_group_id"), ["group_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_mealplan_attendance_household_id"), ["household_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_mealplan_attendance_mealplan_id"), ["mealplan_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_mealplan_attendance_participant_id"), ["participant_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_mealplan_attendance_status"), ["status"], unique=False)

    op.create_table(
        "mealplan_entry_details",
        sa.Column("id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("group_id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("household_id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("mealplan_id", sa.Integer(), nullable=False),
        sa.Column("deadline_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.Column("locked", sa.Boolean(), nullable=False),
        sa.Column("servings_override", sa.Float(), nullable=True),
        sa.Column("cook_participant_id", mealie.db.migration_types.GUID(), nullable=True),
        sa.Column("shopper_participant_id", mealie.db.migration_types.GUID(), nullable=True),
        sa.Column("reminder_sent_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.Column("created_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.Column("update_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["cook_participant_id"],
            ["mealplan_participants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["households.id"],
        ),
        sa.ForeignKeyConstraint(
            ["mealplan_id"],
            ["group_meal_plans.id"],
        ),
        sa.ForeignKeyConstraint(
            ["shopper_participant_id"],
            ["mealplan_participants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("mealplan_id", name="mealplan_entry_details_mealplan_key"),
    )
    with op.batch_alter_table("mealplan_entry_details", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_mealplan_entry_details_cook_participant_id"), ["cook_participant_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_mealplan_entry_details_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_mealplan_entry_details_deadline_at"), ["deadline_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_mealplan_entry_details_group_id"), ["group_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_mealplan_entry_details_household_id"), ["household_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_mealplan_entry_details_locked"), ["locked"], unique=False)
        batch_op.create_index(batch_op.f("ix_mealplan_entry_details_mealplan_id"), ["mealplan_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_mealplan_entry_details_shopper_participant_id"), ["shopper_participant_id"], unique=False
        )

    # Two new event types, so subscribers can be notified about reminders and closed meals.
    with op.batch_alter_table("group_events_notifier_options", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "mealplan_attendance_reminder",
                sa.Boolean(),
                nullable=False,
                default=False,
                server_default=sa.sql.expression.false(),
            )
        )
        batch_op.add_column(
            sa.Column(
                "mealplan_attendance_closed",
                sa.Boolean(),
                nullable=False,
                default=False,
                server_default=sa.sql.expression.false(),
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("group_events_notifier_options", schema=None) as batch_op:
        batch_op.drop_column("mealplan_attendance_closed")
        batch_op.drop_column("mealplan_attendance_reminder")

    with op.batch_alter_table("mealplan_entry_details", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_mealplan_entry_details_shopper_participant_id"))
        batch_op.drop_index(batch_op.f("ix_mealplan_entry_details_mealplan_id"))
        batch_op.drop_index(batch_op.f("ix_mealplan_entry_details_locked"))
        batch_op.drop_index(batch_op.f("ix_mealplan_entry_details_household_id"))
        batch_op.drop_index(batch_op.f("ix_mealplan_entry_details_group_id"))
        batch_op.drop_index(batch_op.f("ix_mealplan_entry_details_deadline_at"))
        batch_op.drop_index(batch_op.f("ix_mealplan_entry_details_created_at"))
        batch_op.drop_index(batch_op.f("ix_mealplan_entry_details_cook_participant_id"))

    op.drop_table("mealplan_entry_details")
    with op.batch_alter_table("mealplan_attendance", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_mealplan_attendance_status"))
        batch_op.drop_index(batch_op.f("ix_mealplan_attendance_participant_id"))
        batch_op.drop_index(batch_op.f("ix_mealplan_attendance_mealplan_id"))
        batch_op.drop_index(batch_op.f("ix_mealplan_attendance_household_id"))
        batch_op.drop_index(batch_op.f("ix_mealplan_attendance_group_id"))
        batch_op.drop_index(batch_op.f("ix_mealplan_attendance_created_at"))

    op.drop_table("mealplan_attendance")
    with op.batch_alter_table("mealplan_absences", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_mealplan_absences_start_date"))
        batch_op.drop_index(batch_op.f("ix_mealplan_absences_participant_id"))
        batch_op.drop_index(batch_op.f("ix_mealplan_absences_household_id"))
        batch_op.drop_index(batch_op.f("ix_mealplan_absences_group_id"))
        batch_op.drop_index(batch_op.f("ix_mealplan_absences_end_date"))
        batch_op.drop_index(batch_op.f("ix_mealplan_absences_created_at"))

    op.drop_table("mealplan_absences")
    with op.batch_alter_table("mealplan_recipe_suggestions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_mealplan_recipe_suggestions_status"))
        batch_op.drop_index(batch_op.f("ix_mealplan_recipe_suggestions_recipe_id"))
        batch_op.drop_index(batch_op.f("ix_mealplan_recipe_suggestions_household_id"))
        batch_op.drop_index(batch_op.f("ix_mealplan_recipe_suggestions_group_id"))
        batch_op.drop_index(batch_op.f("ix_mealplan_recipe_suggestions_created_by_id"))
        batch_op.drop_index(batch_op.f("ix_mealplan_recipe_suggestions_created_at"))

    op.drop_table("mealplan_recipe_suggestions")
    with op.batch_alter_table("mealplan_participants", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_mealplan_participants_user_id"))
        batch_op.drop_index(batch_op.f("ix_mealplan_participants_parent_id"))
        batch_op.drop_index(batch_op.f("ix_mealplan_participants_name"))
        batch_op.drop_index(batch_op.f("ix_mealplan_participants_household_id"))
        batch_op.drop_index(batch_op.f("ix_mealplan_participants_group_id"))
        batch_op.drop_index(batch_op.f("ix_mealplan_participants_created_at"))

    op.drop_table("mealplan_participants")
    with op.batch_alter_table("mealplan_attendance_settings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_mealplan_attendance_settings_household_id"))
        batch_op.drop_index(batch_op.f("ix_mealplan_attendance_settings_group_id"))
        batch_op.drop_index(batch_op.f("ix_mealplan_attendance_settings_created_at"))

    op.drop_table("mealplan_attendance_settings")
    # ### end Alembic commands ###
